---
#
# ========== SCORPIO Lint testing workflow ============
# This workflow runs actionlint (static code analysis) for all github workflows
# The current workflow,
# 1) Checks out SCORPIO source
# 2) Use prebuilt raven actions to run actionlint
#
name: SCORPIO + Actionlint

on:  # yamllint disable-line rule:truthy
  workflow_call:
    inputs:
      branch_name:
        description: 'Branch to run the SCORPIO + Actionlint'
        type: string
        required: true

jobs:
  build_and_test:
    runs-on: ubuntu-latest  # Or other suitable runner

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Run actionlint
        uses: raven-actions/actionlint@v1
        with:
          # Optional configurations:
          shellcheck: true # Lints inline bash scripts
          pyflakes: true   # Lints inline python scripts
